apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "par.fullname" . }}-manager-role
  labels:
  {{- include "par.labels" . | nindent 4 }}
rules:
- apiGroups:
  - record.jmcgrath207.github.com
  resources:
  - as
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - record.jmcgrath207.github.com
  resources:
  - as/finalizers
  verbs:
  - update
- apiGroups:
  - record.jmcgrath207.github.com
  resources:
  - as/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "par.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: par
    app.kubernetes.io/part-of: par
  {{- include "par.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "par.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "par.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'