kubernetesClusterDomain: cluster.local

metrics: false

image:
  repository: ghcr.io/jmcgrath207/par
  imagePullPolicy: Always
  tag: v0.1.0

resources:
  limits:
    cpu: 500m
    memory: 256Mi

requests:
  cpu: 256m
  memory: 128Mi

