kubernetesClusterDomain: cluster.local

metrics: false

image:
  repository: ghcr.io/jmcgrath207/par
  tag: v0.1.0

resources:
  limits:
    cpu: "1"
    memory: 512Mi

requests:
  cpu: 256m
  memory: 128Mi

