apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: system
  labels:
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: proxy
    app.kubernetes.io/component: proxy
    app.kubernetes.io/created-by: par
    app.kubernetes.io/part-of: par
    app.kubernetes.io/managed-by: kustomize
    par.dev: proxy
spec:
  selector:
    matchLabels:
      par.dev: proxy
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: proxy
      labels:
        par.dev: proxy
    spec:
      containers:
        - image: nginx:latest
          name: proxy
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: dns
              containerPort: 53
              protocol: UDP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 256m
              memory: 128Mi
