apiVersion: v1
kind: Service
metadata:
  name: par-proxy
  labels:
    par.dev: proxy
spec:
  selector:
    par.dev: proxy
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
