# REF https://skaffold.dev/docs/references/yaml/?version=v2beta29
apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: par
      docker:
        dockerfile: Dockerfile


profiles:
  - name: staging
    deploy:
      helm:
        releases:
          - name: par-staging
            namespace: par-staging
            createNamespace: true
            chartPath: 'charts/par'
            artifactOverrides:
              image: par
            overrides:
              log_level: debug
              deploy_type: DaemonSet

    portForward:
      - resourceType: Deployment
        resourceName: par
        namespace: par-staging
        port: 9100
        localPort: 9100

  - name: dev
    deploy:
      helm:
        releases:
          - name: par-dev
            namespace: par-dev
            createNamespace: true
            chartPath: 'charts/par'
            artifactOverrides:
              image: par
            overrides:
              log_level: debug
              deploy_type: Deployment

    portForward:
      - resourceType: Deployment
        resourceName: par
        namespace: par-dev
        port: 9100
        localPort: 9100
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: DockerfileDebug

