# REF https://skaffold.dev/docs/references/yaml/?version=v2beta29
apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: par
      docker:
        dockerfile: Dockerfile


profiles:
  - name: staging
    deploy:
      helm:
        hooks:
          before:
            - host:
                command: [ "sleep", "20", "&&",  "kubectl", "apply", "-f", "test_pod.yaml" ]
                os: [ darwin, linux ]
          after:
            - host:
                command: [ "sh", "-c", "kubectl", "delete", "crds", "as.record.jmcgrath207.github.com" ]
                os: [ darwin, linux ]
            - host:
                command: [ "sh", "-c", "kubectl", "delete", "-f", "test_pod.yaml" ]
                os: [ darwin, linux ]
        releases:
          - name: par-staging
            namespace: par-staging
            createNamespace: true
            chartPath: 'charts/par'
            artifactOverrides:
              image: par
            overrides:
              log_level: debug
              deploy_type: DaemonSet


  - name: dev
    deploy:
      helm:
#        hooks:
#          before:
#            - host:
#                command: [  "sh", "-c", "sleep", "20", "&&",  "kubectl", "apply", "--filename", "test_pod.yaml" ]
#                os: [ darwin, linux ]
#          after:
#            - host:
#                command: [ "sh", "-c", "kubectl", "delete", "crds", "as.record.jmcgrath207.github.com" ]
#                os: [ darwin, linux ]
#            - host:
#                command: [ "sh", "-c", "kubectl", "delete", "--filename" , "test_pod.yaml" ]
#                os: [ darwin, linux ]
        releases:
          - name: par-dev
            namespace: par-dev
            createNamespace: true
            chartPath: 'charts/par'
            # Used for passing environmental variables only
            setValueTemplates:
              controllerManager:
                manager:
                  image:
                    repository: "{{.IMAGE_NAME }}"
                    tag: "{{.IMAGE_TAG}}"
            overrides:
              controllerManager:
                manager:
                  enableProbes: false
                  securityContext:
                    runAsNonRoot: false
    portForward:
      - resourceType: Deployment
        resourceName: par-dev-controller-manager
        namespace: par-dev
        port: 56268
        localPort: 56268
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: DockerfileDebug

