apiVersion: v1
kind: Service
metadata:
  name: par-manager
spec:
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: dns
      protocol: UDP
      port: 53
      targetPort: dns
