apiVersion: v1
kind: Service
metadata:
  name: par-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: dns
      protocol: UDP
      port: 53
      targetPort: dns
