apiVersion: v1
kind: Service
metadata:
  name: par-manager
  labels:
    par.dev: manager
spec:
  selector:
    par.dev: manager
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: dns
      protocol: UDP
      port: 53
      targetPort: dns
