apiVersion: v1
kind: Service
metadata:
  name: par-manager
  labels:
    par.dev/manager: "true"
spec:
  selector:
    par.dev/manager: "true"
  ports:
    - name: dns
      protocol: UDP
      port: 53
      targetPort: dns
