apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-par-proxy
  labels:
    par.dev: proxy
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.parProxy.type }}
  selector:
    par.dev: proxy
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.parProxy.ports | toYaml | nindent 2 -}}