---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  labels:
  {{- include "chart.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: par-manager-webhook
  labels:
    par.dev/manager: "true"
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    par.dev/manager: "true"
  ports:
    - name: webhook
      port: 443
      protocol: TCP
      targetPort: webhook

---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: par-mutating-webhook
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: par-manager-webhook
        namespace: {{ .Release.Namespace }}
        path: /mutate-apps-v1-deployment
    failurePolicy: Fail
    name: par-deployment-webhook.par.dev
    rules:
      - apiGroups:
          - apps
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - deployments
    sideEffects: None
