# permissions for end users to edit arecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: arecord-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: par
    app.kubernetes.io/part-of: par
    app.kubernetes.io/managed-by: kustomize
  name: arecord-editor-role
rules:
- apiGroups:
  - dns.par.dev
  resources:
  - arecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.par.dev
  resources:
  - arecords/status
  verbs:
  - get
