# permissions for end users to view arecords.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: arecord-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: par
    app.kubernetes.io/part-of: par
    app.kubernetes.io/managed-by: par-helm
  name: arecord-viewer-role
rules:
- apiGroups:
  - dns.par.dev
  resources:
  - arecords
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dns.par.dev
  resources:
  - arecords/status
  verbs:
  - get
