apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: manager-role-namespaced
  namespace: xxxxxx
rules:
# Used to update the configmap and secrets of proxy config to point to dns manager pod
  - apiGroups:
      - ""
    resources:
      - configmap
      - secrets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
