---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.par.dev
  resources:
  - arecords
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dns.par.dev
  resources:
  - arecords/finalizers
  verbs:
  - update
- apiGroups:
  - dns.par.dev
  resources:
  - arecords/status
  verbs:
  - get
  - patch
  - update
