---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - record.jmcgrath207.github.com
  resources:
  - as
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - record.jmcgrath207.github.com
  resources:
  - as/finalizers
  verbs:
  - update
- apiGroups:
  - record.jmcgrath207.github.com
  resources:
  - as/status
  verbs:
  - get
  - patch
  - update
