name: ci

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.4.0
        with:
          install_only: true
      - uses: azure/setup-helm@v3
      - name: Run e2e
        run: |
          make deploy_e2e
